-- Coordinación de reuniones con clientes. El problema que resuelve: ponerse
-- de acuerdo entre los cuatro socios en un horario lleva varios mensajes de
-- ida y vuelta. El flujo es de encuesta: un socio abre una solicitud con una
-- ventana de días candidatos, cada socio requerido pinta las franjas en que
-- puede, y el sistema cruza esas franjas con lo que ya tienen ocupado en
-- Google Calendar para proponer huecos concretos.
--
-- Decisiones de diseño:
-- - La solicitud ES la reunión: al agendarse se completan inicio/fin y los
--   datos del evento de Google. Evita una segunda tabla que siempre estaría
--   en relación uno a uno con esta.
-- - `socios_requeridos uuid[]` en lugar de tabla puente: son cuatro socios,
--   nunca se consulta el join inverso, y crear la solicitud queda en un solo
--   insert (no hay transacciones desde supabase-js).
-- - `numero`: identidad corta ("REU-7") para referenciarla en lenguaje
--   natural desde MCP, igual que ZQ-N e IDEA-N.

create table public.solicitudes_reunion (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  titulo text not null,
  notas text,
  cliente_id uuid references public.clientes (id),
  proyecto_id uuid references public.proyectos (id),
  duracion_min integer not null default 30
    check (duracion_min in (30, 60)),
  -- Ventana de días candidatos, interpretada en America/Montevideo. Es `date`
  -- y no timestamptz porque "del 5 al 15" es una idea de calendario, no un
  -- instante; las franjas de respuesta sí son instantes absolutos.
  ventana_desde date not null,
  ventana_hasta date not null,
  socios_requeridos uuid[] not null,
  invitar_cliente boolean not null default true,
  estado text not null default 'abierta'
    check (estado in ('abierta', 'agendada', 'cancelada')),
  -- Se completan al agendar.
  inicio timestamptz,
  fin timestamptz,
  google_event_id text,
  -- Email del socio organizador: es el calendario donde vive el evento y a
  -- quién hay que impersonar para borrarlo.
  google_calendar_id text,
  meet_url text,
  agendada_por uuid references public.socios (id),
  agendada_at timestamptz,
  -- metadata.error_calendario guarda el fallo de Google cuando la reunión se
  -- agenda igual pero sin evento.
  metadata jsonb not null default '{}',
  created_by uuid references public.socios (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint solicitudes_reunion_ventana_chk
    check (ventana_hasta >= ventana_desde
           and ventana_hasta <= ventana_desde + 60),
  constraint solicitudes_reunion_requeridos_chk
    check (array_length(socios_requeridos, 1) >= 1),
  constraint solicitudes_reunion_agendada_chk
    check (estado <> 'agendada' or (inicio is not null and fin is not null))
);

create index solicitudes_reunion_estado_idx
  on public.solicitudes_reunion (estado, ventana_desde)
  where deleted_at is null;

-- Para el contador de pendientes del sidebar (socios_requeridos @> [socio]).
create index solicitudes_reunion_requeridos_idx
  on public.solicitudes_reunion using gin (socios_requeridos)
  where deleted_at is null;

create index solicitudes_reunion_inicio_idx
  on public.solicitudes_reunion (inicio)
  where deleted_at is null and estado = 'agendada';

create trigger solicitudes_reunion_updated_at
  before update on public.solicitudes_reunion
  for each row execute function public.set_updated_at();

alter table public.solicitudes_reunion enable row level security;

create policy "socios operan solicitudes de reunion"
  on public.solicitudes_reunion for all
  to authenticated
  using (public.es_socio())
  with check (public.es_socio());

-- ── Respuestas ────────────────────────────────────────────────────────────
-- Una fila por socio que ya respondió. Dos estados se leen de la misma
-- fuente: si no hay fila, no respondió; si `franjas` es [], respondió que no
-- puede en ninguno de esos días.
--
-- Las franjas van en jsonb y no en tabla hija porque responder es siempre un
-- reemplazo completo del set: normalizado serían tres statements (upsert +
-- delete + insert) sin transacción disponible, y un fallo intermedio dejaría
-- media disponibilidad cargada. Acá es un upsert atómico. Nunca se consultan
-- desde SQL: la intersección se calcula en TS porque de todos modos hay que
-- restarle el busy que devuelve Google.

create table public.reunion_respuestas (
  id uuid primary key default gen_random_uuid(),
  solicitud_id uuid not null
    references public.solicitudes_reunion (id) on delete cascade,
  socio_id uuid not null references public.socios (id),
  -- [{"inicio": "2026-08-05T17:00:00.000Z", "fin": "2026-08-05T21:00:00.000Z"}]
  franjas jsonb not null default '[]',
  comentario text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (solicitud_id, socio_id),
  constraint reunion_respuestas_franjas_chk
    check (jsonb_typeof(franjas) = 'array')
);

create index reunion_respuestas_solicitud_idx
  on public.reunion_respuestas (solicitud_id);

create trigger reunion_respuestas_updated_at
  before update on public.reunion_respuestas
  for each row execute function public.set_updated_at();

alter table public.reunion_respuestas enable row level security;

create policy "socios operan respuestas de reunion"
  on public.reunion_respuestas for all
  to authenticated
  using (public.es_socio())
  with check (public.es_socio());

-- Grant explícito para el endpoint MCP (service role key, sin RLS).
grant select, insert, update, delete
  on public.solicitudes_reunion, public.reunion_respuestas
  to service_role;
grant usage, select on sequence public.solicitudes_reunion_numero_seq
  to service_role;
