-- Banco de ideas: las ideas de los socios se capturan crudas (estado
-- 'semilla') y maduran iterando con Claude vía MCP hasta un one-pager
-- estructurado (problema / solución / esfuerzo / impacto / próximos pasos).
-- Sigue los principios del esquema inicial: id uuid, timestamps, created_by,
-- soft delete, estados como catálogo y RLS restringida a socios.
--
-- Decisiones de diseño:
-- - `numero`: identidad corta ("IDEA-7") para referenciarla en lenguaje
--   natural, igual que ZQ-N en el tablero.
-- - Historial explícito en `ideas_versiones` (snapshot jsonb por edición) en
--   lugar de un trigger: quien escribe (server action o MCP) sabe quién es el
--   autor; un trigger con service role no.
-- - `proyecto_id` queda para la graduación (etapa 3): una idea aprobada se
--   vincula al proyecto que generó. Las tareas creadas van en metadata.

create table public.ideas (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  titulo text not null,
  descripcion text,
  -- One-pager: campos de texto comparables entre ideas.
  problema text,
  solucion text,
  esfuerzo text,
  impacto text,
  proximos_pasos text,
  estado text not null default 'semilla'
    check (estado in ('semilla', 'en_exploracion', 'lista', 'aprobada', 'descartada')),
  etiquetas text[] not null default '{}',
  proyecto_id uuid references public.proyectos (id),
  metadata jsonb not null default '{}',
  created_by uuid references public.socios (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index ideas_estado_idx
  on public.ideas (estado, created_at) where deleted_at is null;

create trigger ideas_updated_at
  before update on public.ideas
  for each row execute function public.set_updated_at();

alter table public.ideas enable row level security;

create policy "socios operan ideas"
  on public.ideas for all
  to authenticated
  using (public.es_socio())
  with check (public.es_socio());

-- ── Versiones ─────────────────────────────────────────────────────────────
-- Snapshot del one-pager tras cada creación/edición. `autor_socio_id` null +
-- `autor` texto libre permite atribuir ediciones de un agente ("Claude (MCP)").
-- Índice derivado del contenido real: no lleva soft delete.

create table public.ideas_versiones (
  id uuid primary key default gen_random_uuid(),
  idea_id uuid not null references public.ideas (id) on delete cascade,
  snapshot jsonb not null,
  autor text not null,
  autor_socio_id uuid references public.socios (id),
  created_at timestamptz not null default now()
);

create index ideas_versiones_idea_idx
  on public.ideas_versiones (idea_id, created_at);

alter table public.ideas_versiones enable row level security;

create policy "socios operan versiones de ideas"
  on public.ideas_versiones for all
  to authenticated
  using (public.es_socio())
  with check (public.es_socio());

-- ── Comentarios ───────────────────────────────────────────────────────────
-- Mismo patrón que tareas_comentarios.

create table public.ideas_comentarios (
  id uuid primary key default gen_random_uuid(),
  idea_id uuid not null references public.ideas (id) on delete cascade,
  cuerpo text not null,
  autor text not null,
  autor_socio_id uuid references public.socios (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index ideas_comentarios_idea_idx
  on public.ideas_comentarios (idea_id, created_at)
  where deleted_at is null;

create trigger ideas_comentarios_updated_at
  before update on public.ideas_comentarios
  for each row execute function public.set_updated_at();

alter table public.ideas_comentarios enable row level security;

create policy "socios operan comentarios de ideas"
  on public.ideas_comentarios for all
  to authenticated
  using (public.es_socio())
  with check (public.es_socio());

-- ── Votos ─────────────────────────────────────────────────────────────────
-- Un +1 por socio por idea, para señalar interés y priorizar.

create table public.ideas_votos (
  id uuid primary key default gen_random_uuid(),
  idea_id uuid not null references public.ideas (id) on delete cascade,
  socio_id uuid not null references public.socios (id),
  created_at timestamptz not null default now(),
  unique (idea_id, socio_id)
);

create index ideas_votos_idea_idx on public.ideas_votos (idea_id);

alter table public.ideas_votos enable row level security;

create policy "socios operan votos de ideas"
  on public.ideas_votos for all
  to authenticated
  using (public.es_socio())
  with check (public.es_socio());

-- ── Búsqueda semántica ────────────────────────────────────────────────────
-- Las ideas entran al índice como origen nuevo (el indexador las procesa
-- igual que las decisiones).

alter table public.fragmentos_busqueda
  drop constraint fragmentos_busqueda_origen_check;

alter table public.fragmentos_busqueda
  add constraint fragmentos_busqueda_origen_check
  check (origen in ('drive', 'decision', 'idea'));

-- Grant explícito para el endpoint MCP (service role key, sin RLS): las
-- imágenes nuevas de Postgres de Supabase ya no dan DML a service_role por
-- default privileges sobre tablas creadas por `postgres`.
grant select, insert, update, delete
  on public.ideas, public.ideas_versiones, public.ideas_comentarios,
    public.ideas_votos
  to service_role;
grant usage, select on sequence public.ideas_numero_seq to service_role;
