-- Fase 4: tablero de tareas (kanban propio, sin Jira).
-- Tablero único de la empresa: cada tarea puede colgar de un cliente y/o un
-- proyecto, o ser de empresa (ambos null). Sigue los principios del esquema
-- inicial: id uuid, timestamps, created_by, soft delete, estados como catálogo
-- (check constraint ampliable) y RLS restringida a socios.
--
-- Dos decisiones de diseño que importan:
-- - `numero`: identidad corta y estable para hablar de una tarjeta en lenguaje
--   natural ("ZQ-12"), que es como los LLM y los socios la van a referenciar.
-- - `orden`: numeric, no integer. Al mover una tarjeta entre dos vecinas se
--   guarda el punto medio de sus `orden`, así reordenar toca UNA sola fila.

create table public.tareas (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  titulo text not null,
  descripcion text,
  estado text not null default 'backlog'
    check (estado in ('backlog', 'en_curso', 'en_revision', 'hecho')),
  prioridad text not null default 'media'
    check (prioridad in ('baja', 'media', 'alta', 'urgente')),
  asignado_a uuid references public.socios (id),
  cliente_id uuid references public.clientes (id),
  proyecto_id uuid references public.proyectos (id),
  etiquetas text[] not null default '{}',
  fecha_limite date,
  orden numeric not null default 0,
  metadata jsonb not null default '{}',
  created_by uuid references public.socios (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- El índice del tablero: leer una columna ordenada es el 99% de las queries.
create index tareas_tablero_idx
  on public.tareas (estado, orden) where deleted_at is null;
create index tareas_asignado_idx
  on public.tareas (asignado_a) where deleted_at is null;
create index tareas_cliente_idx
  on public.tareas (cliente_id) where deleted_at is null;
create index tareas_proyecto_idx
  on public.tareas (proyecto_id) where deleted_at is null;

create trigger tareas_updated_at
  before update on public.tareas
  for each row execute function public.set_updated_at();

alter table public.tareas enable row level security;

create policy "socios operan tareas"
  on public.tareas for all
  to authenticated
  using (public.es_socio())
  with check (public.es_socio());

-- ── Comentarios ───────────────────────────────────────────────────────────
-- Hilo de cada tarjeta. `autor_socio_id` null + `autor` texto libre permite
-- que un agente comente identificándose ("Claude (MCP)") sin ser un socio.

create table public.tareas_comentarios (
  id uuid primary key default gen_random_uuid(),
  tarea_id uuid not null references public.tareas (id) on delete cascade,
  cuerpo text not null,
  autor text not null,
  autor_socio_id uuid references public.socios (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index tareas_comentarios_tarea_idx
  on public.tareas_comentarios (tarea_id, created_at)
  where deleted_at is null;

create trigger tareas_comentarios_updated_at
  before update on public.tareas_comentarios
  for each row execute function public.set_updated_at();

alter table public.tareas_comentarios enable row level security;

create policy "socios operan comentarios de tareas"
  on public.tareas_comentarios for all
  to authenticated
  using (public.es_socio())
  with check (public.es_socio());

-- Grant explícito para el endpoint MCP (service role key, sin RLS): las
-- imágenes nuevas de Postgres de Supabase ya no dan DML a service_role por
-- default privileges sobre tablas creadas por `postgres`.
grant select, insert, update, delete
  on public.tareas, public.tareas_comentarios
  to service_role;
grant usage, select on sequence public.tareas_numero_seq to service_role;
