-- Creador de presupuestos, entrega 1: que un presupuesto sea la propuesta
-- entera y que cada uno deje los datos para estimar mejor el siguiente.
--
-- Hasta ahora un presupuesto era una lista de ítems horas × tarifa. La
-- propuesta que se le manda al cliente (contexto, alcance, qué no incluye,
-- fases, precondiciones, costos operativos) vivía afuera, en planillas de
-- Drive, y no quedaba registro de cuántas horas se estimaron ni de cuántas
-- llevó el trabajo. El prompt MCP `armar_propuesta` arma todo eso con Claude
-- y lo guarda acá; el histórico es lo que lee para estimar el próximo.
--
--   presupuestos           código PRES-N, título, cuerpo de la propuesta en
--                          Markdown, qué clase de trabajo es, plazo estimado,
--                          versión de cuál es, y cómo respondió el cliente
--   presupuesto_items      horas internas: lo que estimamos que lleva el
--                          ítem aunque se cobre a precio cerrado
--   tareas                 horas reales dedicadas, para comparar contra lo
--                          estimado cuando se cierre el proyecto
--   configuracion          valores de la empresa editables sin deploy; la
--                          primera es la tarifa por hora de referencia

-- ── Presupuestos ──────────────────────────────────────────────────────────

alter table public.presupuestos
  -- Identidad corta para hablar del presupuesto (PRES-7), igual que ZQ-N en
  -- tareas e IDEA-N en ideas. Las filas existentes se numeran solas.
  add column numero bigint generated by default as identity unique,
  add column titulo text,
  add column contenido text,
  add column tipo text
    check (tipo in ('desarrollo', 'integracion', 'mantenimiento', 'interno')),
  add column etiquetas text[] not null default '{}',
  add column plazo_estimado_semanas numeric(5, 1)
    check (plazo_estimado_semanas > 0),
  -- Versiones: un presupuesto ya enviado no se edita; se crea la versión
  -- siguiente apuntando a la anterior, así queda qué se mandó y qué cambió.
  add column version_de uuid references public.presupuestos (id),
  add column fecha_respuesta date,
  add column motivo_resultado text;

create index presupuestos_version_de_idx
  on public.presupuestos (version_de) where version_de is not null;

grant usage, select on sequence public.presupuestos_numero_seq to service_role;

comment on column public.presupuestos.numero is
  'Código corto PRES-N para referenciar el presupuesto desde el MCP y en conversación.';
comment on column public.presupuestos.titulo is
  'Nombre de la propuesta (ej. "Iber Store Vision"). Es lo que ve el cliente como título del documento.';
comment on column public.presupuestos.contenido is
  'Cuerpo de la propuesta en Markdown: contexto, qué resuelve, alcance, qué no incluye, fases, costos operativos, precondiciones y próximos pasos. Los ítems con precio van en presupuesto_items.';
comment on column public.presupuestos.tipo is
  'Clase de trabajo, mismos valores que proyectos.tipo. Sirve para comparar contra presupuestos parecidos.';
comment on column public.presupuestos.etiquetas is
  'Tecnologías y temas (computer-vision, chatbot, odoo) para encontrar presupuestos comparables.';
comment on column public.presupuestos.plazo_estimado_semanas is
  'Plazo de entrega que se le prometió al cliente, en semanas. Se compara contra las fechas reales del proyecto.';
comment on column public.presupuestos.version_de is
  'Versión anterior de este mismo presupuesto. Null en la primera versión.';
comment on column public.presupuestos.fecha_respuesta is
  'Cuándo respondió el cliente (aprobado o rechazado).';
comment on column public.presupuestos.motivo_resultado is
  'Por qué se aprobó o rechazó, o qué pidió cambiar el cliente. Es lo que más enseña para el próximo.';

-- ── Ítems ─────────────────────────────────────────────────────────────────

alter table public.presupuesto_items
  add column horas_internas numeric(10, 2) check (horas_internas >= 0);

comment on column public.presupuesto_items.horas_internas is
  'Horas que estimamos que lleva el ítem, aunque se cobre a precio cerrado (horas en null y la tarifa como precio). Si es null y el ítem se cobra por hora, valen sus `horas`. Con esto se calcula la tarifa implícita del presupuesto.';

-- ── Tareas ────────────────────────────────────────────────────────────────

alter table public.tareas
  add column horas numeric(8, 2) check (horas >= 0);

comment on column public.tareas.horas is
  'Horas reales dedicadas a la tarjeta. Se cargan al terminarla; la suma por proyecto es lo que se compara contra las horas estimadas del presupuesto.';

-- ── Configuración ─────────────────────────────────────────────────────────

create table public.configuracion (
  clave text primary key,
  valor jsonb not null,
  descripcion text,
  updated_by uuid references public.socios (id),
  updated_at timestamptz not null default now()
);

create trigger configuracion_updated_at
  before update on public.configuracion
  for each row execute function public.set_updated_at();

alter table public.configuracion enable row level security;

create policy "socios operan configuracion"
  on public.configuracion for all
  to authenticated
  using (public.es_socio())
  with check (public.es_socio());

grant select, insert, update, delete on public.configuracion to service_role;

-- Marcador inicial: Sommelier (USD 4.000, ≈ 200 h) y Contabilidad
-- (USD 5.500) dan alrededor de USD 20/h. Se ajusta con
-- `actualizar_configuracion` cuando los socios fijen el número.
insert into public.configuracion (clave, valor, descripcion) values
  (
    'tarifa_hora_usd',
    '20',
    'Tarifa por hora de referencia en USD. Es el precio por defecto de los ítems que se cobran por hora y la vara contra la que se compara la tarifa implícita de cada presupuesto.'
  );
