-- Tablero v5: sprints, al estilo Jira.
--
-- Hasta ahora el tablero era un flujo continuo: las tarjetas iban del backlog
-- a Por hacer y de ahí hasta Hecho, y "Hecho" se limpiaba solo por edad (14
-- días). Con sprints el ciclo se vuelve explícito: se planifica un sprint
-- arrastrando tarjetas del backlog, se inicia (sus tarjetas entran al
-- tablero), se trabaja y al terminar se **completa**: lo hecho queda archivado
-- en el sprint cerrado (desaparece del tablero) y lo que no se terminó vuelve
-- al backlog o pasa al sprint siguiente. Ese "completar" es lo que deja el
-- tablero limpio para arrancar el próximo.
--
-- Decisiones:
-- - Un solo sprint activo a la vez (índice parcial único). El tablero de la
--   empresa es uno solo, así que un sprint es de la empresa; puede tener foco
--   en un proyecto pero no es obligatorio.
-- - `numero` da la identidad corta ("Sprint 3") igual que ZQ-N en tareas.
-- - Las tarjetas de un sprint *planificado* siguen en estado `backlog` (viven
--   en la vista Backlog, agrupadas bajo su sprint); recién al iniciarlo pasan
--   a `por_hacer`. Así el tablero sigue siendo "trabajo comprometido" y la
--   regla vieja del backlog no cambia.
-- - El tablero muestra las tarjetas del sprint activo y las que no tienen
--   sprint (para no esconder nada de lo que ya existía). Las de sprints
--   cerrados no se muestran: eso es la limpieza.

create table public.sprints (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  nombre text not null,
  objetivo text,
  estado text not null default 'planificado'
    check (estado in ('planificado', 'activo', 'cerrado')),
  fecha_inicio date,
  fecha_fin date,
  iniciado_at timestamptz,
  cerrado_at timestamptz,
  proyecto_id uuid references public.proyectos (id),
  metadata jsonb not null default '{}',
  created_by uuid references public.socios (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  check (fecha_fin is null or fecha_inicio is null or fecha_fin >= fecha_inicio)
);

-- Un solo sprint activo a la vez.
create unique index sprints_unico_activo_idx
  on public.sprints (estado)
  where estado = 'activo' and deleted_at is null;

create index sprints_estado_idx
  on public.sprints (estado, numero) where deleted_at is null;

create trigger sprints_updated_at
  before update on public.sprints
  for each row execute function public.set_updated_at();

alter table public.sprints enable row level security;

create policy "socios operan sprints"
  on public.sprints for all
  to authenticated
  using (public.es_socio())
  with check (public.es_socio());

grant select, insert, update, delete on public.sprints to service_role;
grant usage, select on sequence public.sprints_numero_seq to service_role;

-- ── Tarjetas ↔ sprint ─────────────────────────────────────────────────────

alter table public.tareas
  add column sprint_id uuid references public.sprints (id);

-- Leer un sprint (sus tarjetas ordenadas) es la query nueva del backlog y del
-- tablero.
create index tareas_sprint_idx
  on public.tareas (sprint_id, estado, orden) where deleted_at is null;

comment on table public.sprints is
  'Sprints del tablero (estilo Jira). Uno activo a la vez; al completarlo, lo hecho queda archivado en él y lo pendiente vuelve al backlog o pasa al siguiente.';
comment on column public.tareas.sprint_id is
  'Sprint al que pertenece la tarjeta. Null = sin sprint (backlog libre o tablero sin sprint).';
comment on column public.sprints.metadata is
  'Al cerrar guarda `resumen` (hechas, pendientes, puntos) y `pendientes_a` (backlog o número del sprint destino).';
